---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2
inputs:
  - name: pcf-pipelines 
  - name: terraform-state
params:
  PEM:
  ERT_DOMAIN:
run:
  path: pcf-pipelines/tasks/install-pcf-aws/prepare-rds/task.sh
