resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: pcf-pipelines
  type: git
  source:
    uri: git@github.com:pivotal-cf/pcf-pipelines.git
    branch: master
    private_key: {{git_private_key}}

- name: yaml-patch
  type: github-release
  source:
    user: krishicks
    repository: yaml-patch
    access_token: {{github_token}}

- name: pivnet-rc
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: pcf-automation
    access_key_id: {{pivnet_aws_access_key}}
    secret_access_key: {{pivnet_aws_secret_key}}
    product_version: .*-rc\.\d+

- name: pivnet-release
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: pcf-automation
    access_key_id: {{pivnet_aws_access_key}}
    secret_access_key: {{pivnet_aws_secret_key}}

- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.1.0-rc.1
    uri: https://github.com/pivotal-cf/pcf-pipelines
    username: {{github_token}}
    password: x-oauth-basic
    branch: version
    file: version

- name: slack
  type: slack-notification
  source:
    url: {{slack_webhook_url}}

- name: fly
  type: github-release
  check_every: 720h
  source:
    user: krishicks
    repository: fly
    access_token: {{github_token}}

jobs:
- name: bump-patch
  serial_groups: [version]
  plan:
  - put: version
    params: {bump: patch}

- name: bump-minor
  serial_groups: [version]
  plan:
  - put: version
    params: {bump: minor}

- name: test
  on_failure:
    <<: *notify_slack
  plan:
  - aggregate:
    - get: pcf-pipelines
      trigger: true
  - task: test
    file: pcf-pipelines/ci/tasks/test.yml

- name: publish-rc
  serial_groups: [version]
  on_failure:
    <<: *notify_slack
  plan:
  - aggregate:
    - get: pcf-pipelines
      passed: [test]
    - get: yaml-patch
      params:
        globs: ["*linux*"]
    - get: fly

  - put: version
    params: {pre: rc}

  - task: create-release
    file: pcf-pipelines/ci/tasks/create_release.yml
    params:
      AVAILABILITY: Admins Only

  - put: pivnet-rc
    params:
      metadata_file: pivnet-metadata/metadata.yml
      file_glob: pcf-pipelines-release-tarball/*.tgz
      s3_filepath_prefix: {{pivnet_s3_filepath_prefix}}

  - put: pcf-pipelines
    params:
      repository: pcf-pipelines
      tag: version/version
      tag_prefix: v
      only_tag: true

- name: test-rc
  on_failure:
    <<: *notify_slack
  plan:
  - aggregate:
    - get: version
    - get: src
      resource: pcf-pipelines
      passed: [publish-rc]
    - do:
      - get: pivnet-rc
        trigger: true
        passed: [publish-rc]
      - task: unpack-rc
        file: src/tasks/unpack-tarball/task.yml
        input_mapping: { tarball: pivnet-rc }
        output_mapping: { unpacked_tarball: pcf-pipelines-release }

  - task: prepare-workspace
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: czero/cflinuxfs2}
      inputs:
      - name: src
      - name: pcf-pipelines-release
      outputs:
      - name: pcf-pipelines
      run:
        path: bash
        args:
        - -c
        - |
          cp -r src/*.go pcf-pipelines
          cp -r pcf-pipelines-release/pcf-pipelines/* pcf-pipelines

  - task: test
    file: src/ci/tasks/test.yml

- name: update-pipelines
  on_failure:
    <<: *notify_slack
  plan:
  - aggregate:
    - get: version
      passed: [test-rc]
    - get: pcf-pipelines
      passed: [test-rc]
    - get: pivnet-rc
      trigger: true
      passed: [test-rc]

  - task: unpack-rc
    file: pcf-pipelines/tasks/unpack-tarball/task.yml
    input_mapping: { tarball: pivnet-rc }
    output_mapping: { unpacked_tarball: release }

  - aggregate:
    - do:
      - task: create-update-ert-config
        file: pcf-pipelines/ci/tasks/create_update_ert_config.yml
        params:
          <<: *aws_update_pipeline_params
      - task: update-ert-pipeline
        input_mapping: { config: update_ert_config }
        file: pcf-pipelines/ci/tasks/set_pipeline.yml
        params:
          PIPELINE_NAME: lre1-aws-ert-upgrade
          PIPELINE_PATH: release/pcf-pipelines/upgrade-ert/pipeline.yml
          <<: *atc_creds

    - do:
      - task: create-update-buildpacks-config
        file: pcf-pipelines/ci/tasks/create_update_buildpacks_config.yml
        params:
          <<: *aws_update_pipeline_params
      - task: update-buildpacks-pipeline
        input_mapping: { config: update_buildpacks_config }
        file: pcf-pipelines/ci/tasks/set_pipeline.yml
        params:
          PIPELINE_NAME: lre1-aws-buildpacks-upgrade
          PIPELINE_PATH: release/pcf-pipelines/upgrade-buildpacks/pipeline.yml
          <<: *atc_creds

    - do:
      - task: create-upgrade-opsman-aws-config
        file: pcf-pipelines/ci/tasks/create_upgrade_opsman_aws_config.yml
        params:
          <<: *aws_update_opsman_params

      - task: update-upgrade-opsman-aws
        input_mapping: { config: upgrade_opsman_aws_config }
        file: pcf-pipelines/ci/tasks/set_pipeline.yml
        params:
          PIPELINE_NAME: lre1-aws-opsman-upgrade
          PIPELINE_PATH: release/pcf-pipelines/upgrade-ops-manager/aws/pipeline.yml
          <<: *atc_creds

    - do:
      - task: create-upgrade-opsman-gcp-config
        file: pcf-pipelines/ci/tasks/create_upgrade_opsman_gcp_config.yml
        params:
          <<: *gcp_update_opsman_params

      - task: update-upgrade-opsman-gcp
        input_mapping: { config: upgrade_opsman_gcp_config }
        file: pcf-pipelines/ci/tasks/set_pipeline.yml
        params:
          PIPELINE_NAME: upgrade-opsman-gcp
          PIPELINE_PATH: release/pcf-pipelines/upgrade-ops-manager/gcp/pipeline.yml
          <<: *atc_creds

    - do:
      - task: lre2-gcp-create-update-ert-config
        file: pcf-pipelines/ci/tasks/create_params.yml
        params:
          PARAMS_RAW: {{params_lre2_gcp_ert_upgrade}}
      - task: lre2-gcp-update-ert-pipeline
        input_mapping: { config: pipeline_params }
        file: pcf-pipelines/ci/tasks/set_pipeline.yml
        params:
          PIPELINE_NAME: lre2-gcp-ert-upgrade
          PIPELINE_PATH: release/pcf-pipelines/upgrade-ert/pipeline.yml
          <<: *atc_creds

    - do:
      - task: lre3-gcp-create-update-ert-config
        file: pcf-pipelines/ci/tasks/create_params.yml
        params:
          PARAMS_RAW: {{params_lre3_gcp_ert_upgrade}}
      - task: lre3-gcp-update-ert-pipeline
        input_mapping: { config: pipeline_params }
        file: pcf-pipelines/ci/tasks/set_pipeline.yml
        params:
          PIPELINE_NAME: lre3-gcp-ert-upgrade
          PIPELINE_PATH: release/pcf-pipelines/upgrade-ert/pipeline.yml
          <<: *atc_creds

    - do:
      - task: lre2-gcp-opsman-upgrade-config
        file: pcf-pipelines/ci/tasks/create_params.yml
        params:
          PARAMS_RAW: {{params_lre2_gcp_opsman_upgrade}}

      - task: lre2-gcp-opsman-upgrade-pipeline
        input_mapping: { config: pipeline_params }
        file: pcf-pipelines/ci/tasks/set_pipeline.yml
        params:
          PIPELINE_NAME: lre2-gcp-opsman-upgrade
          PIPELINE_PATH: release/pcf-pipelines/upgrade-ops-manager/gcp/pipeline.yml
          <<: *atc_creds

    - do:
      - task: lre3-gcp-opsman-upgrade-config
        file: pcf-pipelines/ci/tasks/create_params.yml
        params:
          PARAMS_RAW: {{params_lre3_gcp_opsman_upgrade}}

      - task: lre3-gcp-opsman-upgrade-pipeline
        input_mapping: { config: pipeline_params }
        file: pcf-pipelines/ci/tasks/set_pipeline.yml
        params:
          PIPELINE_NAME: lre3-gcp-opsman-upgrade
          PIPELINE_PATH: release/pcf-pipelines/upgrade-ops-manager/gcp/pipeline.yml
          <<: *atc_creds

- name: publish-release
  serial_groups: [version]
  plan:
  - aggregate:
    - get: version
      passed: [update-pipelines]
      params: {bump: final}
    - get: pcf-pipelines
      passed: [update-pipelines]
    - get: yaml-patch
      params:
        globs: ["*linux*"]
    - get: fly

  - task: create-release
    file: pcf-pipelines/ci/tasks/create_release.yml
    params:
      AVAILABILITY: Selected User Groups Only

  - put: pivnet-release
    params:
      metadata_file: pivnet-metadata/metadata.yml
      file_glob: pcf-pipelines-release-tarball/*.tgz
      s3_filepath_prefix: {{pivnet_s3_filepath_prefix}}

  - put: pcf-pipelines
    params:
      repository: pcf-pipelines
      tag: version/version
      tag_prefix: v
      only_tag: true

  on_failure:
    <<: *notify_slack
  on_success:
    do:
    - task: create-slack-notification
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: concourse/buildroot
            tag: curl
        inputs:
        - name: pivnet-release
        outputs:
        - name: notification-text
        run:
          path: sh
          args:
          - -ce
          - |
            release_id=$(cat pivnet-release/metadata.json | jq .Release.ID)
            cat > notification-text/text <<EOF
              Deployed pcf-pipelines final release to https://network.pivotal.io/products/pcf-automation#/releases/$release_id
            EOF
    - put: slack
      params:
        text_file: notification-text/text
        silent: true

    - put: version
      params: {bump: final}

    - put: version
      params: {bump: patch, pre: rc}

aws_update_pipeline_params: &aws_update_pipeline_params
  IAAS_TYPE: {{iaas_type}}
  PIVNET_TOKEN: {{pivnet_token}}
  PIVNET_POLL_INTERVAL: {{pivnet_poll_interval}}
  CF_API_URI: {{aws_cf_api_uri}}
  CF_USER: {{aws_cf_user}}
  CF_PASSWORD: {{aws_cf_password}}
  CHECK_NEW_OPSMAN_EVERY: 24h
  OPSMAN_MAJOR_MINOR_VERSION: {{opsman_major_minor_version}}
  OPSMAN_TIMEOUT_SECONDS: {{opsman_timeout_seconds}}
  OPSMAN_URI: {{opsman_uri}}
  OPSMAN_ADMIN_USERNAME: {{opsman_admin_username}}
  OPSMAN_ADMIN_PASSWORD: {{opsman_admin_password}}

gcp_update_opsman_params: &gcp_update_opsman_params
  OPSMAN_PROJECT: {{upgrade_opsman_gcp_opsman_gcp_project}}
  OPSMAN_ZONE: {{upgrade_opsman_gcp_opsman_gcp_zone}}
  OPSMAN_DISKIMAGE_NAME: {{upgrade_opsman_gcp_opsman_gcp_diskimage_name}}
  OPSMAN_GCP_CREDFILE_CONTENTS: {{upgrade_opsman_gcp_opsman_gcp_credfile_contents}}
  EXISTING_OPSMAN_VM_NAME: {{upgrade_opsman_gcp_existing_opsman_vm_name}}
  OPSMAN_URI: {{upgrade_opsman_gcp_opsman_uri}}
  OPSMAN_ADMIN_USERNAME: {{upgrade_opsman_gcp_opsman_admin_username}}
  OPSMAN_ADMIN_PASSWORD: {{upgrade_opsman_gcp_opsman_admin_password}}
  OPSMAN_TIMEOUT_SECONDS: {{opsman_timeout_seconds}}
  OPSMAN_MAJOR_MINOR_VERSION: {{upgrade_opsman_gcp_opsman_major_minor_version}}
  PIVNET_TOKEN: {{pivnet_token}}
  CHECK_NEW_OPSMAN_EVERY: 24h

aws_update_opsman_params: &aws_update_opsman_params
  AWS_SECRET_ACCESS_KEY: {{upgrade_opsman_aws_aws_secret_access_key}}
  AWS_REGION: {{upgrade_opsman_aws_aws_region}}
  AWS_VPC_ID: {{upgrade_opsman_aws_aws_vpc_id}}
  AWS_ACCESS_KEY_ID: {{upgrade_opsman_aws_aws_access_key_id}}
  EXISTING_OPSMAN_VM_NAME: {{upgrade_opsman_aws_existing_opsman_vm_name}}
  OPSMAN_URI: {{upgrade_opsman_aws_opsman_uri}}
  OPSMAN_ADMIN_USERNAME: {{upgrade_opsman_aws_opsman_admin_username}}
  OPSMAN_ADMIN_PASSWORD: {{upgrade_opsman_aws_opsman_admin_password}}
  OPSMAN_TIMEOUT_SECONDS: {{opsman_timeout_seconds}}
  OPSMAN_MAJOR_MINOR_VERSION: {{opsman_major_minor_version}}
  PIVNET_TOKEN: {{pivnet_token}}
  CHECK_NEW_OPSMAN_EVERY: 24h

atc_creds: &atc_creds
  ATC_EXTERNAL_URL: {{atc_external_url}}
  ATC_BASIC_AUTH_USERNAME: {{fly_basic_auth_username}}
  ATC_BASIC_AUTH_PASSWORD: {{fly_basic_auth_password}}
  ATC_TEAM_NAME: {{atc_team_name}}

notify_slack: &notify_slack
  put: slack
  params:
    text: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME failed: $ATC_EXTERNAL_URL/builds/$BUILD_ID"
