---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudopsci/eu-ci
    tag: stable
run:
  path: /bin/bash
  args:
  - -exc
  - |-
    #!/usr/bin/env bash
    omen toggle-errands --action disable
params:
  OPSMAN_HOSTNAME:
  OPSMAN_PASSWORD:
  OPSMAN_USER: